### ISSUE TITLE
[VK-32]: Crash - open app in the offline mode

### ISSUE THREAD

**Issue by nethergrim** [nethergrim/vk_client#53]
Steps to reproduce:
* sign in
* turn off wifi and cellular data
* open the app
observe crash:
`java.lang.NullPointerException: Attempt to read from field 'int com.vk.sdk.api.VKError.errorCode' on a null object reference
            at com.vk.sdk.VKSdk$1.onError(VKSdk.java:419)
            at com.vk.sdk.api.VKRequest$2.run(VKRequest.java:397)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by nethergrim** [comment]
Fixed, merged to develop https://github.com/nethergrim/vk_client/pull/54
